### ISSUE TITLE
Identify additional NEON datasets w/ potential relevance to project

### ISSUE THREAD

**Issue by KristinaRiemer** [genophenoenvo/neon-datasets#2]

**Comment by dlebauer** [comment]
Is this helpful for plant cover and diversity data? Would be nice if it works with or could work with neonstore outputs https://github.com/admahood/neondiversity

**Comment by KristinaRiemer** [comment]
Resulting from 12/3/2020 conversation, summary info about six additional NEON datasets (2 phenology and 4 diversity) have been added to the README. See [the pull request](https://github.com/genophenoenvo/neon-datasets/pull/8) for that.
