### ISSUE TITLE
Improve forecasted weather dataset

### ISSUE THREAD

**Issue by KristinaRiemer** [genophenoenvo/neon-datasets#37]
- [x] Add date and time column: `x <- noaa_fc %>% mutate(date = startDate + lubridate::hours(time))`
- [x] Harmonize weather variables with those in Daymet data
- [x] TBD: how to deal with multiple ensembles? 
  - either generate ensemble of forecasts and summarize -OR-
  - use median values

**Comment by jessicaguo** [comment]
[PR 42](https://github.com/genophenoenvo/neon-datasets/pull/42), which supersedes [PR 39](https://github.com/genophenoenvo/neon-datasets/pull/39).
