### ISSUE TITLE
Explore black cottonwood phenophase data

### ISSUE THREAD

**Issue by jessicaguo** [genophenoenvo/neon-datasets#49]
Data received from collaborators at ORNL on black cottonwood common gardens. Curate phenophase data and communicate with Wellington and Kai about data provenance questions. Develop visualizations on Rpubs. 
- [x] Email for clarification about data naming
- [x] Create private repo and upload .txt files 
- [x] Initial data exploration: file sizes, uniqueness

**Comment by KristinaRiemer** [comment]
Are you taking on the phenophase data then? If that's the case, I can be responsible for curating the weather data.

**Comment by jessicaguo** [comment]
Emailed Kai Feng about additional data documentation. Need particular clarification on dates - the same replicates were sampled up to 3 times, but only a subset of the data files have associated dates. Very important to get the dates. 

Private [repo](https://github.com/genophenoenvo/cottonwood-phenophases) initiated, with .txt files. Initial exploration suggested the repeated sampling (above), and also that the unique IDs are not fully unique. The distribution of duplicates is:
![image.png](https://images.zenhubusercontent.com/5f513e94d41e1d43610542ee/17baa5f7-2315-4944-922b-eb4b93ed1955)
Erroneous duplication could account for the small end of the spectrum, but otherwise there are a lot. Will try next to find the duplications for each file and whether the phenophase matches or not.
