### ISSUE TITLE
Curate and standardize black cottonwood phenophases

### ISSUE THREAD

**Issue by jessicaguo** [genophenoenvo/neon-datasets#56]
Follow up to #50
- [x] Meet with Wellington on Aug 2, document data description
- [x] Provide Wellington with list of files with missing dates and duplicate genotypes from site-year-block combinations
- [x] Decide how to standardize file names across 76 files
- [x] Update 01_explore.R to accomodate new naming conventions
- [ ] create figures comparing bud set and bud break between genotypes, plots, years, 
- [x] Hillary Cooper brainstorming
- [ ] Provide Hillary with summary of data available, including efforts to model budburst or budset 3.5

**Comment by jessicaguo** [comment]
I explored the Placerville 2010 Bud Set data, which have date and 3 sets of sampling dates. However, even restricting to the most data-rich genotypes (with 9 points or more), only some span the range of the bud set levels (1-6). 
![image.png](https://images.zenhubusercontent.com/5f513e94d41e1d43610542ee/44633cca-57b2-4e76-8765-35730d63530e)

I am not sure how to derive a response variable from these data. >1000 genotypes were planted at this site, but genotypes were only replicated 3 times (blocks). 474 genotypes were sampled 3 times, which yields a maximum of 9 data points from which to derive a phenotype. @dlebauer, any thoughts on how to proceed?

**Comment by KristinaRiemer** [comment]
We did talk the other day about one option, of binning all the responses into two categories, e.g., bud set values below 3 vs bud set values 3 and above. We just need some sort of justification for choosing what those categories are.

**Comment by jessicaguo** [comment]
For phenophase data, I feel we need some kind of date as a response variable. It's also not great that the plants were surveyed at most 3 times, because they clearly missed the transition period for some genotypes.
