### ISSUE TITLE
Package PEG project components for publication

### ISSUE THREAD

**Issue by jessicaguo** [genophenoenvo/neon-datasets#63]
As discussed at UA team meeting. 
Jessica:
- [x] Pull out growth rate modeling into separate repo
- [x] Document and test reproducibility
- [ ] Add growth rates to latest version of MAC season 4 and 6 data?

Kristina:
- [x] summarize NEON data curation (should NEON datasets be separated? more clearly described?)
- [x] separate EFI forecasts into separate repo and update README
- [ ] Add model details to new models repo (see #70)
- [x] Add automated submission details to new models repo
- [x] Archive code on Cyverse (ask Tyson)

**Comment by KristinaRiemer** [comment]
Moved `models` folder, with all commits, from [neon-datasets](https://github.com/genophenoenvo/neon-datasets) into a new repo [neon-efi-challenge](https://github.com/genophenoenvo/neon-efi-challenge). Updated the two READMEs.

Need to replace the neon-datasets repo on the submission server with the neon-efi-challenge one, and test that it's still working correctly.

**Comment by KristinaRiemer** [comment]
Archived curated NEON datasets on CyVerse in [genophenoenvo NEON data folder](https://de.cyverse.org/data/ds/iplant/home/shared/genophenoenvo/data/neon?selectedOrder=asc&selectedOrderBy=name&selectedPage=0&selectedRowsPerPage=100).

**Comment by jessicaguo** [comment]
Follow up issues created
