### ISSUE TITLE
Archive 2 versions of repo

### ISSUE THREAD

**Issue by jessicaguo** [genophenoenvo/neon-datasets#79]
- [x] tag different stages of the repo
- [x] Create releases
- [x] Bug Tyson for Zenodo access
- [x] Ask Debasmita to update README
- [ ] archive current repo as 2.0, inclusive of spring and fall 2021

**Comment by dlebauer** [comment]
https://github.com/citation-file-format/citation-file-format

**Comment by jessicaguo** [comment]
Created followup #83 to help Debasmita with documentation
