### ISSUE TITLE
Curate initial phenology dataset

### ISSUE THREAD

**Issue by KristinaRiemer** [genophenoenvo/neon-datasets#9]
Get plant flowering dates across sites from phenology measurements dataset [DP1.10055.001](https://data.neonscience.org/data-products/DP1.10055.001).

**Comment by KristinaRiemer** [comment]
Initial curated phenology measurements dataset, across all sites and all dates, is in #12. This includes the script for curating the data, the resulting dataset, and an updated readme. 

@dlebauer I don't know if you want to look this over?

**Comment by dlebauer** [comment]
looks great, thanks!
